In [1]:
import os
import warnings
warnings.filterwarnings("ignore")  
os.chdir("../../..")

In [2]:
import copy
from pathlib import Path
import numpy as np
import pandas as pd
import pytorch_lightning as pl
from pytorch_lightning.callbacks import EarlyStopping, LearningRateMonitor
from pytorch_lightning.loggers import TensorBoardLogger
import torch

from pytorch_forecasting import Baseline, TemporalFusionTransformer, TimeSeriesDataSet
from pytorch_forecasting.data import GroupNormalizer
from pytorch_forecasting.metrics import SMAPE, PoissonLoss, QuantileLoss
from pytorch_forecasting.models.temporal_fusion_transformer.tuning import optimize_hyperparameters

In [35]:
date=pd.date_range(start='2021/01/01',periods=1082,freq='d')
data=pd.DataFrame(np.random.randn(1082,3),columns=['A','B','C'])
data['date']=date
# add time index
data["time_idx"]=data['date'].dt.year*12+data['date'].dt.month
data["time_idx"]-=data["time_idx"].min()  #按年、月份设置索引
# data['date'].dt.weekofyear 输出当前日期为一年的第几周
# add additional features 
data["month"] = data.date.dt.month.astype(str).astype("category")   # categories have be strings
'''
transform:Call function producing a like-indexed Series on each group and return a Series having the same indexes as the original object.
例: grouped.transform(lambda x: (x - x.mean()) / x.std())
'''
data['A_mean']=data.groupby('month',observed=True).A.transform("mean")    #按month求A列的均值
    filled with the transformed values.
data

             A         B         C       date  time_idx month    A_mean
0    -1.778283 -0.321081  0.837192 2021-01-01         0     1  0.192756
1     0.125001 -0.292223  0.650074 2021-01-02         0     1  0.192756
2     0.510933 -0.902860 -0.886443 2021-01-03         0     1  0.192756
3     1.019896  0.960692  0.064621 2021-01-04         0     1  0.192756
4    -0.845948  0.567268  1.821366 2021-01-05         0     1  0.192756
...        ...       ...       ...        ...       ...   ...       ...
1077  0.203330 -0.489498 -0.129675 2023-12-14        35    12  0.111070
1078  0.415353  1.394505 -0.744979 2023-12-15        35    12  0.111070
1079  1.819536  0.385729  0.911125 2023-12-16        35    12  0.111070
1080  1.687120  1.225148 -0.154486 2023-12-17        35    12  0.111070
1081  1.438226 -0.444351  0.733430 2023-12-18        35    12  0.111070

[1082 rows x 7 columns]

In [38]:
help(data.groupby('month',observed=True).A.transform)

Help on method transform in module pandas.core.groupby.generic:

transform(func, *args, engine=None, engine_kwargs=None, **kwargs) method of pandas.core.groupby.generic.SeriesGroupBy instance
    Call function producing a like-indexed Series on each group and
    return a Series having the same indexes as the original object
    filled with the transformed values.

    Parameters
    ----------
    f : function
        Function to apply to each group.

        Can also accept a Numba JIT function with
        ``engine='numba'`` specified.

        If the ``'numba'`` engine is chosen, the function must be
        a user defined function with ``values`` and ``index`` as the
        first and second arguments respectively in the function signature.
        Each group's index will be passed to the user defined function
        and optionally available for use.

        .. versionchanged:: 1.1.0
    *args
        Positional arguments to pass to func.
    engine : str, default None
        * ``'cython'`` : Runs the function through C-extensions from cython.
        * ``'numba'`` : Runs the function through JIT compiled code from numba.
        * ``None`` : Defaults to ``'cython'`` or the global setting ``compute.use_numba``

        .. versionadded:: 1.1.0
    engine_kwargs : dict, default None
        * For ``'cython'`` engine, there are no accepted ``engine_kwargs``
        * For ``'numba'`` engine, the engine can accept ``nopython``, ``nogil``
          and ``parallel`` dictionary keys. The values must either be ``True`` or
          ``False``. The default ``engine_kwargs`` for the ``'numba'`` engine is
          ``{'nopython': True, 'nogil': False, 'parallel': False}`` and will be
          applied to the function

        .. versionadded:: 1.1.0
    **kwargs
        Keyword arguments to be passed into func.

    Returns
    -------
    Series

    See Also
    --------
    Series.groupby.apply : Apply function ``func`` group-wise and combine
        the results together.
    Series.groupby.aggregate : Aggregate using one or more
        operations over the specified axis.
    Series.transform : Call ``func`` on self producing a Series with the
        same axis shape as self.

    Notes
    -----
    Each group is endowed the attribute 'name' in case you need to know
    which group you are working on.

    The current implementation imposes three requirements on f:

    * f must return a value that either has the same shape as the input
      subframe or can be broadcast to the shape of the input subframe.
      For example, if `f` returns a scalar it will be broadcast to have the
      same shape as the input subframe.
    * if this is a DataFrame, f must support application column-by-column
      in the subframe. If f also supports application to the entire subframe,
      then a fast path is used starting from the second chunk.
    * f must not mutate groups. Mutation is not supported and may
      produce unexpected results. See :ref:`gotchas.udf-mutation` for more details.

    When using ``engine='numba'``, there will be no "fall back" behavior internally.
    The group data and group index will be passed as numpy arrays to the JITed
    user defined function, and no alternative execution attempts will be tried.

    .. versionchanged:: 1.3.0

        The resulting dtype will reflect the return value of the passed ``func``,
        see the examples below.

    Examples
    --------

    >>> df = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar',
    ...                           'foo', 'bar'],
    ...                    'B' : ['one', 'one', 'two', 'three',
    ...                           'two', 'two'],
    ...                    'C' : [1, 5, 5, 2, 5, 5],
    ...                    'D' : [2.0, 5., 8., 1., 2., 9.]})
    >>> grouped = df.groupby('A')
    >>> grouped.transform(lambda x: (x - x.mean()) / x.std())
              C         D
    0 -1.154701 -0.577350
    1  0.577350  0.000000
    2  0.577350  1.154701
    3 -1.154701 -1.000000
    4  0.577350 -0.577350
    5  0.577350  1.000000

    Broadcast result of the transformation

    >>> grouped.transform(lambda x: x.max() - x.min())
       C    D
    0  4  6.0
    1  3  8.0
    2  4  6.0
    3  3  8.0
    4  4  6.0
    5  3  8.0

    .. versionchanged:: 1.3.0

        The resulting dtype will reflect the return value of the passed ``func``,
        for example:

    >>> grouped[['C', 'D']].transform(lambda x: x.astype(int).max())
       C  D
    0  5  8
    1  5  9
    2  5  8
    3  5  9
    4  5  8
    5  5  9

In [22]:
data.month.max

<bound method NDFrame._add_numeric_operations.<locals>.max of 0        1
1        1
2        1
3        1
4        1
        ..
1077    12
1078    12
1079    12
1080    12
1081    12
Name: month, Length: 1082, dtype: category
Categories (12, object): ['1', '10', '11', '12', ..., '6', '7', '8', '9']>